def pomLocation = "configuration-api-parent"
def dockerRepoName = "sleepingtalent/configuration-api"
def targetLocation = "configuration-api-parent/configuration-api/target"
def version

node {
  def img
  def newVersion

  stage('Checkout') {
    checkout scm
    def pom = readMavenPom file: pomLocation+'/pom.xml'
    version = pom.version
  }

  stage('Build Application') {
    sh 'mvn -B -V -U -e -f '+pomLocation+'/pom.xml clean install'
  }

  stage('Tag Release'){
    sh "mvn -B -V -U -e -f " + pomLocation + "/pom.xml release:clean release:prepare"
  }

  stage('Package Image') {
    img = docker.build(dockerRepoName+':'+version, targetLocation)
  }

  stage('Push Image') {
    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
        img.push()
        img.push("latest")
    }
  }

  stage('Remove Local Image') {
       sh 'docker rmi -f registry.hub.docker.com/'+dockerRepoName+':latest'
       sh 'docker rmi -f registry.hub.docker.com/'+dockerRepoName+':'+version
       sh 'docker rmi -f '+dockerRepoName+':'+version
  }

}