apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: config-api
spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
              app: config-api
              tier: configuration
        spec:
            containers:
            - name: config-api
              image: sleepingtalent/configuration-api:1.0.73
              env:
              - name: GIT_CONFIG_URL
                value: https://github.com/BabcockEMTDevelopment/prod-configuration-properties
              ports:
              - containerPort: 1111
            imagePullPolicy: Always


